# Generated by Django 3.1.2 on 2020-10-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0010_establishments_is_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishments',
            name='days_in_advance',
        ),
    ]
