# Generated by Django 3.1.2 on 2020-10-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0012_auto_20201021_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishments',
            name='days_in_advance',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='patrons',
            name='email',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='patrons',
            name='first_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='patrons',
            name='second_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='patrons',
            name='user_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='patrons',
            name='user_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patrons',
            name='user_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patrons',
            name='user_handphone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patrons',
            name='user_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
