# Generated by Django 3.1.2 on 2020-11-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0019_rsv_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(default='SOME STRING', max_length=50)),
                ('business_email', models.CharField(default='SOME STRING', max_length=50)),
                ('business_incharge_person', models.CharField(default='SOME STRING', max_length=50)),
                ('business_password', models.CharField(default='SOME STRING', max_length=50)),
                ('business_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('business_mail_address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
