# Generated by Django 3.1.2 on 2020-10-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(default='SOME STRING', max_length=50)),
                ('business_email', models.CharField(default='SOME STRING', max_length=50)),
                ('business_incharge_person', models.CharField(default='SOME STRING', max_length=50)),
                ('business_password', models.CharField(default='SOME STRING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='establishment_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_username', models.CharField(default='-', max_length=50)),
                ('e_company', models.CharField(default='-', max_length=50)),
                ('e_location', models.CharField(default='-', max_length=300)),
                ('e_maxcapacity', models.CharField(default='-', max_length=3)),
                ('e_opentime', models.CharField(default='-', max_length=20)),
                ('e_closetime', models.CharField(blank=True, max_length=20, null=True)),
                ('e_openmonday', models.BooleanField(default=False)),
                ('e_opentuesday', models.BooleanField(default=False)),
                ('e_openwednesday', models.BooleanField(default=False)),
                ('e_openthursday', models.BooleanField(default=False)),
                ('e_openfriday', models.BooleanField(default=False)),
                ('e_opensaturday', models.BooleanField(default=False)),
                ('e_opensunday', models.BooleanField(default=False)),
                ('e_othercloseday1', models.CharField(blank=True, max_length=20, null=True)),
                ('e_othercloseday2', models.CharField(blank=True, max_length=20, null=True)),
                ('e_othercloseday3', models.CharField(blank=True, max_length=20, null=True)),
                ('e_othercloseday4', models.CharField(blank=True, max_length=20, null=True)),
                ('e_othercloseday5', models.CharField(blank=True, max_length=20, null=True)),
                ('e_openendvisittime', models.BooleanField(default=False)),
                ('e_defaulttime', models.CharField(default='-', max_length=20)),
                ('e_maxduration', models.CharField(default='-', max_length=20)),
                ('e_maxgroupsize', models.CharField(default='-', max_length=20)),
                ('e_graceperiod', models.CharField(default='-', max_length=20)),
                ('e_allowchange', models.BooleanField(default=False)),
                ('e_allowshuffle', models.BooleanField(default=False)),
                ('e_shuffleperiod', models.CharField(blank=True, max_length=20, null=True)),
                ('e_inadvance', models.BooleanField(default=False)),
                ('e_advanceblock', models.CharField(blank=True, max_length=20, null=True)),
                ('e_sendreminder', models.BooleanField(default=False)),
                ('e_autoapproval', models.BooleanField(default=False)),
                ('e_reportingperiod', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unique', models.CharField(default='-', max_length=50)),
                ('user_id', models.CharField(default='-', max_length=50)),
                ('intends', models.CharField(blank=True, max_length=300, null=True)),
                ('notification', models.CharField(blank=True, max_length=300, null=True)),
                ('datetime', models.DateTimeField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unique', models.CharField(default='-', max_length=50)),
                ('user_id', models.CharField(default='-', max_length=50)),
                ('establishment', models.CharField(default='-', max_length=50)),
                ('location', models.CharField(default='-', max_length=100)),
                ('Reservation_date', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('Reservation_time', models.CharField(default='-', max_length=50)),
                ('Reservation_duration', models.CharField(default='-', max_length=50)),
                ('Number_people', models.CharField(default='-', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='users_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=300)),
                ('user_country', models.CharField(max_length=50)),
                ('user_city', models.CharField(max_length=50)),
                ('user_postal', models.CharField(max_length=20)),
                ('user_aboutme', models.CharField(max_length=50)),
            ],
        ),
    ]
