# Generated by Django 3.1.2 on 2020-10-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment_register',
            name='e_sublocation',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='establishment_register',
            name='e_type',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='establishment_register',
            name='e_unique_id',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
