# Generated by Django 3.1.2 on 2020-10-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0002_auto_20201012_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_register',
            name='business_contact',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='business_register',
            name='business_mail_address',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
