# Generated by Django 3.1.2 on 2020-10-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0004_auto_20201012_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reservation',
            name='establishment_id',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='user_reservation',
            name='status',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
