# Generated by Django 3.1.2 on 2020-10-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0005_auto_20201017_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='establishments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('sublocs', models.TextField(max_length=100)),
                ('max_cap', models.CharField(max_length=50)),
                ('open_days', models.CharField(max_length=50)),
                ('open_time', models.CharField(max_length=50)),
                ('close_time', models.CharField(max_length=50)),
                ('default_duration', models.CharField(max_length=50)),
                ('days_in_advance', models.CharField(max_length=50)),
                ('max_group_size', models.CharField(max_length=50)),
                ('report_period', models.CharField(default='14', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='patrons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='queries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=50)),
                ('patron', models.CharField(max_length=50)),
                ('establishment', models.CharField(max_length=50)),
                ('n_person', models.CharField(max_length=50)),
                ('time_in', models.CharField(max_length=50)),
                ('time_out', models.CharField(max_length=50)),
                ('intent', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('loc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=50)),
                ('patron', models.CharField(max_length=50)),
                ('establishment', models.CharField(max_length=50)),
                ('n_person', models.CharField(max_length=50)),
                ('time_in', models.CharField(max_length=50)),
                ('time_out', models.CharField(max_length=50)),
                ('intent', models.CharField(max_length=50)),
                ('step', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('selection', models.CharField(max_length=50)),
            ],
        ),
    ]
