# Generated by Django 3.1.2 on 2020-10-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0007_auto_20201021_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishments',
            name='company',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
