# Generated by Django 3.1.2 on 2020-10-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0008_establishments_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishments',
            name='contact',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
