# Generated by Django 3.1.2 on 2020-10-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0009_establishments_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishments',
            name='is_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
