# Generated by Django 3.1.2 on 2020-10-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0013_auto_20201024_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='establishment_register',
        ),
        migrations.DeleteModel(
            name='users_name',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='action',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='selection',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='step',
        ),
        migrations.AddField(
            model_name='queries',
            name='action',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='queries',
            name='selection',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='queries',
            name='step',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='reservations',
            name='loc',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='reservations',
            name='status',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
