# Generated by Django 3.1.2 on 2020-10-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0014_auto_20201026_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrons',
            name='username',
            field=models.TextField(max_length=50),
        ),
    ]
