# Generated by Django 3.1.2 on 2020-10-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0015_auto_20201026_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrons',
            name='email',
            field=models.TextField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='patrons',
            name='first_name',
            field=models.TextField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='patrons',
            name='second_name',
            field=models.TextField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='patrons',
            name='user_address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patrons',
            name='user_city',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patrons',
            name='user_country',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patrons',
            name='user_handphone',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patrons',
            name='user_postal',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
