# Generated by Django 3.1.2 on 2020-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0017_auto_20201026_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='business_register',
        ),
        migrations.DeleteModel(
            name='user_notification',
        ),
        migrations.DeleteModel(
            name='user_reservation',
        ),
        migrations.AlterField(
            model_name='establishments',
            name='days_in_advance',
            field=models.IntegerField(default='-'),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='default_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='max_cap',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='max_group_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='report_period',
            field=models.IntegerField(default='14'),
        ),
    ]
