# Generated by Django 3.1.2 on 2020-11-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nus', '0020_business_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='qry_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('establishment', models.TextField(max_length=50)),
                ('timestamp', models.TextField(max_length=50)),
                ('period', models.TextField(max_length=50)),
                ('n_total', models.TextField(max_length=50)),
                ('DuplicateExist', models.TextField(max_length=50)),
                ('FinalizeReservation', models.TextField(max_length=50)),
                ('OfferSlots', models.TextField(max_length=50)),
                ('OversizedGroup', models.TextField(max_length=50)),
                ('PlaceNotAvail', models.TextField(max_length=50)),
                ('OutsideOpenDays', models.TextField(max_length=50)),
                ('InThePast', models.TextField(max_length=50)),
                ('OnHoldReservation', models.TextField(max_length=50)),
                ('TooSoon', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='rsv_report',
            name='hourly',
            field=models.TextField(max_length=1000),
        ),
    ]
